apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer

spec:
  acme:
    email: trapsysad@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
            ingressTemplate:
              metadata:
                annotations:
                  traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      - dns01:
          cloudDNS:
            project: trap-sysad
            serviceAccountSecretRef:
              # Referenced in kustomize-config.yaml for hash suffix substitution
              name: dns-solver
              key: key.json
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: dns-solver
              key: key.json
